##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Images of Ancient Music Database
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: This database contains images associated with the music of ancient Greece and Rome and other images connected with Greco-Roman antiquity and its reception. 
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "A Collection from the WashU Department of Classics

A Guide to the Entry Metadata:

Publication Date: Date entry was photographed.

Topics: "Tags" that you can sort the database by. Look at the bar on the left of the page under the subject field and select appropriate keywords to your inquiry.

Rights: Creative Commons Rights.

A_repository_entry_link: Extremely helpful links to origin repositories/other databases that have publicly uploaded the same entry online. Here you can gather significant amounts of additional metadata, often straight from museums and credible actors. 

Accession_number: The direct identification number the origin repository uses to identify the depicted item on their database. Provided occasionally but not always. 

Addeddate: When entry was added to IA database.

Collection_added: Shows that this is under WashU Classics.

Collection_grouping: Extremely important when entries belong to collections. This means that there are multiple database pictures of this same exhibit focusing on different items pictured, i.e. two clarinets in one photo will likely have two unique entries, in which both can be found by searching this collection grouping name.

Grouping: Notes if entry belongs to a collection or if there are multiple photos of the same object depicting additional angles (if yes, follow process above).

Identifier: Unique string of numbers associated with only one entry.

Earliest_date and Latest_date: The most probable time period/year we could find for when an item was actually created, or at the very least obtained by a museum. Often a span of time, i.e. earliest date=750BC and latest date = 690BC. If vague, try checking repository entry link if there is one.

Relationships: Occasionally entries in collections/alternate angles will also have this category, which gives the name of these related files. One could then directly find related entries by searching the given filename on the database. 

Many Thanks to All Contributors: 

Tim Moore - Project Leader and Principal Investigator
Michael Whisenhunt - Photographer 
Sophie Hsu - Metadata Development and IA Database Architect
Jackie Clay - Metadata Development
Jin Lee - Metadata Development
Carolyn Pohl - Metadata Development
Jordan Coley - Metadata Development

Mitch Sumner - Digital Collections Advisor
Douglas Knox - Advisor
Shannon Davis - Advisor"
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: SH

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: finalcopy

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
